name: Build Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: beiyuouo/readme-action@main
        with:
          blog_rss_link: https://youngfish42.github.io/index.xml
          blog_limit: 1
          blog_time_format: "%a, %d %b %Y %H:%M:%S %z"
          douban_name: 187848884
          douban_limit: 1
          commit_message: Update readme rss by readme-action
          time_zone: "Asia/Shanghai"

  # update-wakatime:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: zylele/waka-readme@master
  #       with:
  #         SHOW_TITLE: true
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
